version: "3.9"

services:
  api:
    image: puzynjailya/skypro_hw26:$GITHUB_RUN_ID-$GITHUB_REF_NAME
    ports:
      - 80:80
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5