version: "3.9"

services:
  api:
    build:
      context: .
    image: puzynjailya/skypro_hw26
    ports:
      - 80:80
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: app_db
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5