name: deploying_container
on: [push]
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code pull
        uses: actions/checkout@v2
      - name: deploy docker image
        run: docker build -t puzynjailya/skypro_hw26:$GITHUB_RUN_ID-$GITHUB_REF_NAME .
      - name: docker login
        run: echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: docker push
        run: docker push puzynjailya/skypro_hw26:$GITHUB_RUN_ID-$GITHUB_REF_NAME
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_deploy
    env:
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: code pull
        uses: actions/checkout@v2
      - name: render configs
        run: |
          mkdir deploy
          cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
      - name: move files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy/docker-compose.yaml"
          target: "app_ci"
          strip_components: 1

      - name: deploy docker-compose
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.PASSWORD }}
            sript: | 
              cd app_ci
              echo ${{ secrets.PASSWORD }} | sudo -S docker-compose up -d
              


